export const BACKEND_CATEGORIES = [
  {
    id: 'python',
    slug: 'python',
    name: 'Python Ecosystem',
    description: 'Core syntax, OOP, dunder methods, generators, GIL, asyncio, and packaging.',
    iconName: 'Terminal',
    badgeColor: 'bg-emerald-50',
    orderIndex: 1,
  },
  {
    id: 'java',
    slug: 'java',
    name: 'Java & Spring Ecosystem',
    description: 'JVM internals, GC algorithms, multithreading, concurrency locks, streams, and Spring Boot.',
    iconName: 'Coffee',
    badgeColor: 'bg-amber-50',
    orderIndex: 2,
  },
  {
    id: 'dsa',
    slug: 'dsa',
    name: 'Data Structures & Algorithms',
    description: 'Linear & tree structures, graphs, dynamic programming, backtracking, and complexity patterns.',
    iconName: 'Cpu',
    badgeColor: 'bg-blue-50',
    orderIndex: 3,
  },
  {
    id: 'systems',
    slug: 'systems',
    name: 'Memory & Systems Programming',
    description: 'Stack/Heap allocation, virtual memory, OS scheduling, deadlocks, networking sockets, and profiling.',
    iconName: 'HardDrive',
    badgeColor: 'bg-purple-50',
    orderIndex: 4,
  },
  {
    id: 'fullstack',
    slug: 'fullstack',
    name: 'Full Stack & Web Engineering',
    description: 'Modern React, state machines, Node.js event loop, FastAPI, PostgreSQL indexing, and web security.',
    iconName: 'Layers',
    badgeColor: 'bg-cyan-50',
    orderIndex: 5,
  },
  {
    id: 'aiml',
    slug: 'aiml',
    name: 'AI, ML & Deep Learning',
    description: 'Numpy, Pandas, feature engineering, backpropagation, CNN/RNN/Transformers, PyTorch, and MLOps.',
    iconName: 'Brain',
    badgeColor: 'bg-rose-50',
    orderIndex: 6,
  },
  {
    id: 'genai',
    slug: 'genai',
    name: 'Generative AI & Agentic Systems',
    description: 'LLM tokenization, RAG chunking & vector search, prompt routing, tool calling, and MCP architecture.',
    iconName: 'Sparkles',
    badgeColor: 'bg-indigo-50',
    orderIndex: 7,
  },
  {
    id: 'architecture',
    slug: 'architecture',
    name: 'Software Architecture & Leadership',
    description: 'System design, event-driven microservices, distributed consistency, CAP theorem, and tech mentoring.',
    iconName: 'Network',
    badgeColor: 'bg-slate-50',
    orderIndex: 8,
  },
];

export const BACKEND_QUESTIONS = [
  {
    id: 'q-py-gil-01',
    slug: 'cpython-global-interpreter-lock-parallelism',
    title: 'Explain the Global Interpreter Lock (GIL) in CPython and How to Achieve True Parallelism',
    categoryId: 'python',
    subjectId: 'py-memory',
    topicId: 'topic-py-gil',
    minExperienceYears: 2,
    maxExperienceYears: 15,
    difficulty: 'advanced',
    interviewType: 'screening',
    estimatedTimeMinutes: 15,
    expectedAnswerDepth: 'Detailed architectural walkthrough of CPython reference counting, bytecode evaluation loop, and concurrency alternatives.',
    statement: 'What is the Global Interpreter Lock (GIL) in CPython, why does it exist, and how does it affect CPU-bound versus I/O-bound multi-threaded programs? How can a high-throughput Python service achieve true multicore parallelism?',
    shortAnswer: 'The GIL is a mutex that protects access to Python objects, preventing multiple native threads from executing CPython bytecodes at once. It exists primarily because CPython’s memory management uses non-thread-safe reference counting. For I/O-bound tasks, threads release the GIL while waiting on sockets/disk, making threading effective. For CPU-bound tasks, threads thrash on GIL contention, so multicore parallelism requires multiprocessing, process pools, native C/Rust extensions (which release the GIL), or Python 3.13+ free-threaded builds (PEP 703).',
    detailedExplanation: 'CPython tracks object lifecycles using reference counting supplemented by a cyclic garbage collector. Every time an object is referenced, its internal ob_refcnt field increments. Without a global lock, concurrent threads updating reference counts across shared objects would trigger race conditions and memory corruption.',
    practicalExample: 'In image processing, running 4 threads resizing images runs slower than 1 single thread due to GIL contention. Converting the service to ProcessPoolExecutor scales throughput linearly across all physical CPU cores.',
    pythonCode: 'from concurrent.futures import ProcessPoolExecutor\n\ndef cpu_task(n: int) -> int:\n    return sum(i * i for i in range(n))\n\nwith ProcessPoolExecutor() as executor:\n    results = list(executor.map(cpu_task, [10000000] * 4))',
    javaCode: 'import java.util.stream.*;\n\nLongStream.of(10000000L, 10000000L).parallel().map(n -> n * 2).toArray();',
    timeComplexity: 'O(N) CPU operations distributed across P processes -> O(N / P) wall-clock time.',
    spaceComplexity: 'O(P * M) process base footprint.',
    commonMistakes: [
      'Assuming Python threading makes mathematical loops or image manipulation faster.',
      'Forgetting that multiprocessing copies data unless using shared memory or memory-mapped files.',
    ],
    followUpQuestions: [
      'How does Python 3.13 PEP 703 eliminate the GIL without degrading single-threaded performance?',
      'How does the cyclic garbage collector detect reference cycles that reference counting misses?',
    ],
    prerequisites: ['Python basics', 'Threads vs Processes'],
    tags: ['Python', 'GIL', 'CPython', 'Concurrency', 'Memory Management'],
    status: 'published',
  },
  {
    id: 'q-dsa-sliding-01',
    slug: 'longest-substring-without-repeating-characters',
    title: 'Longest Substring Without Repeating Characters (Optimal Sliding Window)',
    categoryId: 'dsa',
    subjectId: 'dsa-arrays',
    topicId: 'topic-dsa-sliding-window',
    minExperienceYears: 0,
    maxExperienceYears: 10,
    difficulty: 'intermediate',
    interviewType: 'coding',
    estimatedTimeMinutes: 20,
    expectedAnswerDepth: 'Derive from O(N^2) brute force to O(N) sliding window with hash map storing last seen index.',
    statement: 'Given a string s, find the length of the longest substring without duplicate characters. Provide optimal solutions in Python and Java, analyzing time and space complexity.',
    shortAnswer: 'Maintain a dynamic sliding window [left, right]. Use a hash map storing each character’s most recent index. When a duplicate character is encountered within the current window, move the left pointer forward past the duplicate index (left = max(left, last_seen[char] + 1)). Update the character’s position and compute max_len = max(max_len, right - left + 1). This runs in O(N) time and O(min(N, charset)) space.',
    detailedExplanation: 'Initialize left = 0 and max_length = 0. Iterate right pointer from 0 to len(s) - 1. If char is in table and table[char] >= left, set left = table[char] + 1. Update table[char] = right and max_length = max(max_length, right - left + 1).',
    practicalExample: 'Input s = "abcabcbb". Window expands "abc" (length 3), jumps left pointer past duplicate a, output is 3.',
    pythonCode: 'def length_of_longest_substring(s: str) -> int:\n    char_map = {}\n    left = 0\n    max_len = 0\n    for right, c in enumerate(s):\n        if c in char_map and char_map[c] >= left:\n            left = char_map[c] + 1\n        char_map[c] = right\n        max_len = max(max_len, right - left + 1)\n    return max_len',
    javaCode: 'import java.util.HashMap;\npublic class Solution {\n    public static int lengthOfLongestSubstring(String s) {\n        HashMap<Character, Integer> map = new HashMap<>();\n        int left = 0, maxLen = 0;\n        for (int right = 0; right < s.length(); right++) {\n            char c = s.charAt(right);\n            if (map.containsKey(c) && map.get(c) >= left) left = map.get(c) + 1;\n            map.put(c, right);\n            maxLen = Math.max(maxLen, right - left + 1);\n        }\n        return maxLen;\n    }\n}',
    timeComplexity: 'O(N) single pass.',
    spaceComplexity: 'O(min(N, charset size)).',
    commonMistakes: [
      'Forgetting char_map[c] >= left check, causing left to jump backward.',
      'Failing on empty string input.',
    ],
    followUpQuestions: [
      'What if the input contains full UTF-8 emojis?',
      'How would you return the actual substring instead of just length?',
    ],
    prerequisites: ['Hash maps', 'Two pointer concept'],
    tags: ['DSA', 'Arrays', 'Strings', 'Sliding Window', 'Two Pointers'],
    status: 'published',
  },
  {
    id: 'q-genai-rag-01',
    slug: 'production-rag-chunking-hybrid-search-reranking',
    title: 'Production RAG Architecture: Chunking, Hybrid Search, Vector Embeddings & Reranking',
    categoryId: 'genai',
    subjectId: 'genai-rag',
    topicId: 'topic-genai-rag-pipeline',
    minExperienceYears: 2,
    maxExperienceYears: 18,
    difficulty: 'advanced',
    interviewType: 'system_design',
    estimatedTimeMinutes: 25,
    expectedAnswerDepth: 'End-to-end design covering document ingestion, semantic chunking, dense vector retrieval vs sparse BM25, cross-encoder rerankers, and hallucination guardrails.',
    statement: 'How do you design an enterprise-grade Retrieval-Augmented Generation (RAG) system for a knowledge base of 500,000 technical manuals? How do you overcome context loss from chunking, semantic retrieval misses, and LLM hallucinations?',
    shortAnswer: 'A production RAG architecture requires a multi-stage pipeline: (1) Ingestion with semantic/recursive chunking; (2) Multi-representation indexing pairing dense vector embeddings with sparse keyword indexes (BM25); (3) Hybrid Search with Reciprocal Rank Fusion (RRF); (4) Cross-Encoder Reranking on top 50 candidates; (5) Context compression/prompt assembly with citation constraints; and (6) Post-generation validation via fact-checking guardrails.',
    detailedExplanation: 'Reciprocal Rank Fusion merges dense vector matches with keyword matches. Cross-encoders examine query and document candidate pairs jointly, computing deep attention scores.',
    practicalExample: 'In medical manuals, BM25 ensures rare drug brand names match exactly while dense vectors match symptom descriptions.',
    pythonCode: 'def rrf_score(dense_rank: int, sparse_rank: int, k: int = 60) -> float:\n    return (1.0 / (k + dense_rank)) + (1.0 / (k + sparse_rank))',
    javaCode: 'public double rrfScore(int denseRank, int sparseRank, int k) {\n    return (1.0 / (k + denseRank)) + (1.0 / (k + sparseRank));\n}',
    timeComplexity: 'HNSW vector search: O(log N). Cross-encoder: O(K * SeqLen^2) on top K=50 candidates.',
    spaceComplexity: 'Vector index: ~4 bytes * dimensions * N vectors.',
    commonMistakes: [
      'Sending too many raw chunks into LLM without reranking.',
      'Naive character-based chunking that breaks sentence structure.',
    ],
    followUpQuestions: [
      'How does GraphRAG outperform vector RAG on multi-hop questions?',
      'How do you handle embedding drift when upgrading models?',
    ],
    prerequisites: ['Vector embeddings', 'Information retrieval'],
    tags: ['Generative AI', 'RAG', 'Vector Search', 'LLMs', 'System Design'],
    status: 'published',
  },
];
